version: "3.2"

services:
  robackend1:
    build:
      context: .
    restart: unless-stopped
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=fuzzydb
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - APPLICATION_NAME=Read-only backend 1
      - URL=http://localhost:9091/api/v1/api
    ports:
      - "8070:8080"
    links:
      - "fuzzy-db:fuzzydb"
    depends_on:
      - fuzzy-db
  robackend2:
    build:
      context: .
    restart: unless-stopped
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=fuzzydb
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - APPLICATION_NAME=Read-only backend 2
      - URL=http://localhost:9091/api/v1/api
    ports:
      - "8071:8080"
    links:
      - "fuzzy-db:fuzzydb"
    depends_on:
      - fuzzy-db
  mainbackend:
    build:
      context: .
    restart: unless-stopped
    environment:
      - POSTGRES_USER=administr
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_HOST=fuzzydb
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - APPLICATION_NAME=Main backend
      - URL=http://localhost:9091/api/v1/api
    links:
      - "fuzzy-db:fuzzydb"
    ports:
      - "8072:8080"
  mirror:
    build:
      context: .
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_HOST=fuzzydb
      - POSTGRES_PORT=5432
      - POSTGRES_DB=emptyfuzzydb
      - APPLICATION_NAME=Mirror backend
      - URL=http://localhost:9091/mirror1/api/v1/api/
    links:
      - "mirror-fuzzy-db:fuzzydb"
    ports:
      - "8081:8080"
    depends_on:
      - mirror-fuzzy-db
  mirror-fuzzy-db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret_password
    ports:
      - "5728:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data2:/var/lib/postgresql/data

  fuzzy-db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret_password
    ports:
      - "5727:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=serovamn@student.bmstu.ru
      - PGADMIN_DEFAULT_PASSWORD=123456
      - traefik.frontend.pgadmin4.rule=Host(`host.example.com`) && PathPrefix(`/pgadmin4`)
  nginx:
    image: 'byjg/nginx-extras:master'
    ports:
      - "9091:9091"
    links:
      - robackend1
      - robackend2
      - mainbackend
      - mirror
      - pgadmin
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/static
    depends_on:
      - robackend1
      - robackend2
      - mainbackend
      - mirror
      - pgadmin
