server:
  servlet:
    context-path: /api
    application-display-name: ${APPLICATION_NAME}
  forward-headers-strategy: framework
spring:
  servlet:
    multipart:
      resolve-lazily: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
springdoc:
  api-docs:
    path: /v1/docs/src
  swagger-ui:
    path: /v1/docs/swagger
    disable-swagger-default-url: true
  #  use-management-port: true
  show-actuator: true
custom:
  server-url: ${URL}